name: commit
run-name: ${{ github.actor }}
on:
  push:
    branches:
      - main

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - run: echo Getting ready to send data to the webhook
      - name: Send data to the webhook
        uses: Ilshidur/action-discord@master
        with:
          args: >
            {
              "embeds": [
                {
                  "title": "New commit",
                  "description": "New commit by ${{ github.actor }}",
                  "color": 16711680,
                  "fields": [
                    {
                      "name": "Commit message",
                      "value": "${{ github.event.head_commit.message }}"
                    },
                    {
                      "name": "Commit URL",
                      "value": "${{ github.event.head_commit.url }}"
                    }
                  ]
                }
              ]
            }
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}